### ISSUE TITLE
legato_qs_9x75_eb_rpi_7inch demo does not work

### ISSUE THREAD

**Issue by SLKomatsu** [Microchip-MPLAB-Harmony/gfx_apps_sam_9x7#1]
I have compiled and attempted to deploy the project with the specified hardware (7 inch RPI touch screen and SAM9X75-DDR3-EB-REV3) and the screen remains black.
[harmony.zip](https://github.com/Microchip-MPLAB-Harmony/gfx_apps_sam_9x7/files/12730825/harmony.zip)

**Comment by MHGC** [comment]
Hi, are you using the 22-pin-to-15-pin DSI cable? Are you connecting the cable per the application document?

**Comment by SLKomatsu** [comment]
I have resolved this issue with help from Microchip support. I was using a 22 to 15 pin cable, but the pinout of the cable I was using was incorrect.

**Comment by MHGC** [comment]
Great. Thanks!
